AWSTemplateFormatVersion: 2010-09-09
Description: |
 intance is runned with cl 
  
Parameters:
  Keyname:
   Description: choose your keypair
   Type: AWS::EC2::KeyPair::KeyName


  
Resources:
  MySecgrp:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: enabled http and ssh # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 
  myec2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bef6cc322bfff646
      InstanceType: t2.micro
      KeyName: !Ref Keyname
      SecurityGroupIds: 
        - !Ref MySecgrp
      Tags: 
        - Key: Name 
          Value: !Sub Web Server of ${AWS::StackName}

      UserData: !Base64 |
        #! /bin/bash
        yum update -y
        yum install python3
        pip3 install flask
        cd /home/ec2-user
        FOLDER="https://raw.githubusercontent.com/hafize0106/my-project-aws/main/Project-001-Roman-Numerals-Converter/"
        wget ${FOLDER}/app.py
        mkdir templates && cd templates
        wget ${FOLDER}/templates/index.html 
        wget ${FOLDER}/templates/result.html
        cd ..
        python3 app.py
        

  
Outputs: 
  DNSNAME:
    Value: !Sub 
      - http://${Publicadress}
      - Publicadress: !GetAtt myec2.PublicDnsName 

